### ISSUE TITLE
functionsわからん

### ISSUE THREAD

**Issue by H37kouya** [u-lab/uu-circles2020#76]
```
[debug] [2020-06-17T02:56:18.644Z] [runtime-status] [6204] Checked functions.config() {"config":{}} 
[debug] [2020-06-17T02:56:18.645Z] [runtime-status] [6204] Error in handleMessage: {"frb":{"cwd":"C:\\Users\\kouya\\code\\uucircle\\uu-circle2020\\functions","projectId":"uu-circle20","triggerId":"","emulators":{},"socketPath":"\\\\?\\pipe\\C:\\Users\\kouya\\code\\uucircle\\uu-circle2020\\functions\\6204"},"opts":{"nodeBinary":"C:\\Program Files\\nodejs\\node.exe"}} => TypeError: Cannot set property config of #<Object> which has only a getter: TypeError: Cannot set property config of #<Object> which has only a getter
    at C:\Users\kouya\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:455:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\kouya\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
[warn] !  functions: Cannot set property config of #<Object> which has only a getter
[warn] !  Your function was killed because it raised an unhandled error.
```

**Comment by H37kouya** [comment]
起動手順と失敗
1. assets/test/jsonの内容を assets/jsonにコピー
2. ` npm run build:o ` nuxt のビルド
3. ` sh build.sh ` .nuxtをfunctions側にコピーしたい
4. ` firebase serve `  ← 動かない。
